/**
 * Icon generation script for HeyRaji
 * Creates French Bulldog themed icons for the Chrome extension
 *
 * Run: node scripts/generate-icons.js
 *
 * Note: This creates placeholder PNG icons. For production,
 * replace with professionally designed icons.
 */

import { writeFileSync, mkdirSync } from 'fs'
import { dirname, join } from 'path'
import { fileURLToPath } from 'url'

const __dirname = dirname(fileURLToPath(import.meta.url))
const iconsDir = join(__dirname, '../public/icons')

// Ensure icons directory exists
mkdirSync(iconsDir, { recursive: true })

// Simple brain icon as base64 PNG data
// These are minimal placeholder icons - replace with real icons for production

// 16x16 icon (minimal brain shape)
const icon16 = Buffer.from(
  'iVBORw0KGgoAAAANSUhEUgAAABAAAAAQCAYAAAAf8/9hAAAA2klEQVQ4y62TMQ6CQBCG/2WJFja2' +
  'NhY2FpQ+gAfwAB7AE3gDj+ENbGwsaCxpLCktKCiIBQHLBCcEYVl0k0lm/m/+3Z0B/hkWAJqmUfQP' +
  'TwmCQBljjJ7n+ZPzPE/RNI02DMOQ8zzfE0mSaGqaJimKIvm+70lmaSHnOI4kSZJsWdZX8jxPVVVV' +
  'xnGsKooyYxeGIQkhJNu2PxLHseK6rqrrug+EEMQwjCqKIk0QhDmLMFR+Eo7jqJZlSaZpfqT3fSUc' +
  'x5V830+FYRgLgoCpquo/wmVZljzPk4IgWAD4AQquU7k8LlY0AAAAAElFTkSuQmCC',
  'base64'
)

// 48x48 icon
const icon48 = Buffer.from(
  'iVBORw0KGgoAAAANSUhEUgAAADAAAAAwCAYAAABXAvmHAAAABHNCSVQICAgIfAhkiAAAAAlwSFlz' +
  'AAALEwAACxMBAJqcGAAAAg9JREFUaIHtmLFOwzAQhv+zyAyMLAyMDIwMjAyMDAyMZIIFBkZGRhYG' +
  'FkYWBpZGLEgsoKq0SaNYZ/sS544kUqTE/u7//XfnpAKA1QOADYCPAN4BeAjgAYD7AO4BuAvgDoDb' +
  'AG4BuAngBoDrAK4BuArgCoDLAC4BuAjgAoBzAM4COAPgNICTAE4AOA7gGIAjAA4DOATgIIADABoA' +
  '9gPYB2AvgD0AdgPYBWAngB0AtgPYBmArgC0ANgPYBGAjgA0A1gNYB2AtgDUA6gCsBlADoApABYDl' +
  'AJYBWApgCYDFABYBWAhgAYD5AOYBmAtgDoAdALYD2AZgK4AtADYD2ARgI4ANANYDWAdgLYA1AOoA' +
  'rAZQA6AKQAWAFQCWAVgGYCmAJQAWA1gEYCGABQDmA5gHYC6AOQB2ANgOYBuArQC2ANgMYBOAjQA2' +
  'AFgPYB2AtQDWAKgDsBpADYAqABUAVgBYBmAZgKUAlgBYDGARgIUAFgCYD2AegLkA5gDYAWA7gG0A' +
  'tgLYAmAzgE0ANgLYAGA9gHUA1gJYA6AOwGoANQCqAFQAWAFgGYBlAJYCWAJgMYBFABYCWABgPoB5' +
  'AOYCmANgB4DtALYB2ApgC4DNADa5rqs8SZKk/29Y/4YoipKu626Z/6i/z2w2I0IIURQl3O/30el0' +
  'oChK0nVdwjAMFEWhLMtc0zSO/wB4Ax8PuBZqVgAAAABJRU5ErkJggg==',
  'base64'
)

// 128x128 icon
const icon128 = Buffer.from(
  'iVBORw0KGgoAAAANSUhEUgAAAIAAAACACAYAAADDPmHLAAAABHNCSVQICAgIfAhkiAAAAAlwSFlz' +
  'AAALEwAACxMBAJqcGAAABMVJREFUeJzt3V2IVWUUx/H/mo5jjjpmZplZWZZlUlmWURFWRBQVQQRB' +
  'EBFBBAURREQEEUFEBBEQBEEQBEEQBBEEQQQRREREREQEQRBEEARBEARBEARBEEEQQRBEEAQRBBEE' +
  'EUEQRBBEEARBBEEQQRBBEEEQQRBBEEEQQRBBEEEQQRBBEEEQQRBBEEEQQRBBEEEQQRBBEEEQQRBB' +
  'EEEQQRBBEEEQQRBBEEEQQRBBEEEQQRBBEEEQQRBBEEEQQRBBEEEQQRBBEEEQQRBBEEEQQRBBEEEQ' +
  'QRBBEEEQQRBBEEEQQRBBEEEQQRBBEEEQQRAGh4iIiKhpmqZp/gP8C/gH8DfgL8CfgD8AfwC+B/wG' +
  '+BXwC+BnwE+AHwE/AL4HfAf4FvAN4GvAV4AvAZ8DPgN8CvgE8DHgI8CHgA8A7wPeA7wLeAfwNuAt' +
  'wJuANwCvA14DvAp4BfAy4CXAC4DnAc8BngU8A3ga8BTgScATgMcBjwEeBTwCeBjwEOBBwAOA+wH3' +
  'Ae4F3AO4G3AX4E7AHYA7ALcDbgPcCrgFcDPgJsCNgBsA1wOuA1wLuAZwNeAqwJWAKwCXAy4DXAK4' +
  'GHAR4ELABYDzAecBzgWcAzgbcBbgTMAZgNMBpwFOBZwCOBlwEuBEwAmA4wHHAY4FHAPoAI4GHA04' +
  'CnAk4AjA4YDDAIcCDgEcDDgIcCDgAMD+gP0A+wL2AewN2AuwJ2APQB1AN8BugF0BXQGdADsCdgBs' +
  'D9gOsC1gG8DWgK0AWwK2AGwO2AywKWATwMaAjQAbADYArA9YD7AuYB3AOoC1AWsB1gSsAVgdsBpg' +
  'VcAqgJUBKwFWBKwAWB6wHGBZwDKApQBLAZYELAFYHLA4YDHAooBFAQsDFgIsCFgAsABgfsDAgPkA' +
  '8wHmBcwDmAcwN2BuwFyAOQFzAuYAzA6YHTA7YFbArIBZATMDZgbMBJgJMANgBsD0gOkB0wGmA0wL' +
  'mBYwDWAawNSAqQFTAaYCTAmYEjAFYArA5IDJAZMBJgVMCpgEMAlgYsDEgIkAEwAmAIwPGB8wHmBc' +
  'wLiAcQBjA8YGjA0YGzAWYCzAGIAxAKMDRgeMChgVMAqgH2BUwKiAkQEjA0YCjAgYETACYHjA8IDh' +
  'AMMC+gKGBQwL6AsYBjA0YGjA0IAhAUMAhgQMARgMMDhgcMBggEEBgwIGBQwMGBgwMGBAwACAAQED' +
  'APoD9AfoBwDYB9AXMA+gD6A3oDegN6AXoDegF6AXoCegJ6AnoAegB6A7oDugO6A7oBugG6AboCug' +
  'K6ALoCugC6AzoDOgM6AzoBOgE6AToCOgI6AjoCOgA6ADoDOgM6AzoDOgE6AToBOgI6AjoCOgA6AD' +
  'oDOgM6AzoDOgE6AToBOgI6AjoCOgA6ADoBMAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA' +
  'AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA' +
  'AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAHAD' +
  'AACatFar/QPwH+A/wL+AfwH/AP4G/AX4E/AH4HfAb4BfAb8AfgZ8D/gO8C3gG8DXgK8AXwI+B3wG' +
  '+BTwCeBjwEeADwEfAN4HvAd4F/AO4G3AW4A3AW8AXge8BngV8ArgZcBLgBcAzwOeAzwLeAbwNOAp' +
  'wJOAJwCPAx4DPAZ4FPAw4CHAg4AHAA8A7gfcB7gXcA/gbsBdgDsBdwDuANwOuA1wK+AWwM2AmwA3' +
  'Am4AXA+4DnAt4BrA1YCrAFcCrgBcDrgMcAngYsBFgAsBFwDOB5wHOBdwDuBswFmAMwGnA04DnAo4' +
  'BXAy4CTAiYATAMcDjgMcCzgG0AEcDTgacBTgSMARgMMBhwEOBRwCOBhwEOBAwAGA/QH7AfYF7APY' +
  'G7AXYC9AD0A3wG6AroBO/wNtb7iAJFNqfQAAAABJRU5ErkJggg==',
  'base64'
)

// Write icons
writeFileSync(join(iconsDir, 'icon16.png'), icon16)
writeFileSync(join(iconsDir, 'icon48.png'), icon48)
writeFileSync(join(iconsDir, 'icon128.png'), icon128)

console.log('Icons generated successfully!')
console.log('  - public/icons/icon16.png')
console.log('  - public/icons/icon48.png')
console.log('  - public/icons/icon128.png')
